import { Site, TeamMember, Notification } from './types'

export const TEAM: TeamMember[] = [
  { id: 'valentin', name: 'Valentin',  role: 'pm',  av: 'V', online: true  },
  { id: 'james',    name: 'James',     role: 'ss',  av: 'J', online: true  },
  { id: 'sarah',    name: 'Sarah',     role: 'ss',  av: 'S', online: false },
  { id: 'marco',    name: 'Marco',     role: 'tl',  av: 'M', online: true  },
  { id: 'luke',     name: 'Luke',      role: 'sub', av: 'L', online: false },
]

export const INITIAL_SITES: Site[] = [
  {
    id: 'oxford',
    name: 'Oxford Street Retail',
    shortName: 'Oxford St',
    address: '142 Oxford St, Paddington NSW 2021',
    client: 'Scentre Group',
    color: '#F5A623',
    status: 'active',
    progress: 62,
    budget: 1850000,
    spent: 1140000,
    phase: 'Structure R+2',
    teamIds: ['valentin', 'james', 'sarah', 'marco'],
    emails: [
      {
        id: 'ox-e1',
        fromName: 'BSS Concrete',
        from: 'accounts@bssconcrete.com.au',
        subject: 'Invoice #BSS-2847 – Concrete Supply Oxford St',
        body: 'Please find attached invoice #BSS-2847 for concrete supply to Oxford Street site.\n\nConcrete supply – 180m³ @ $120/m³: $21,600\nPump hire: $800\n\nTotal: $22,400 (inc. GST)\n\nPayment due: 30 days from invoice date.\n\nPlease contact us if you have any queries.',
        date: '9:14 AM',
        att: 'Invoice_BSS-2847.pdf',
        read: false,
        type: 'invoice',
        siteId: 'oxford',
      },
      {
        id: 'ox-e2',
        fromName: 'City of Sydney Council',
        from: 'development@cityofsydney.nsw.gov.au',
        subject: 'DA Compliance Notice – 142 Oxford St',
        body: 'This notice is to advise that a compliance inspection is scheduled for the above property.\n\nInspection Date: Friday 25 April 2025\nTime: 10:00 AM – 12:00 PM\n\nPlease ensure the following documentation is available:\n- Current noise management plan\n- Construction hours compliance records\n- Dust suppression measures\n\nFailure to comply may result in stop-work orders.',
        date: 'Yesterday',
        att: null,
        read: false,
        type: 'compliance',
        siteId: 'oxford',
      },
      {
        id: 'ox-e3',
        fromName: 'Arch Studio Collins',
        from: 'drawings@archstudio.com.au',
        subject: 'Revised Structural Drawings – Column Grid Change',
        body: 'Hi team,\n\nPlease find attached the revised structural drawings for Oxford Street.\n\nKey change: Column C4 has been relocated 300mm east per structural engineer review. This affects the concrete pour schedule for R+2 slab.\n\nPlease review and confirm with your structural engineer before proceeding.\n\nRevision: Rev C – 20 April 2025\n\nRegards,\nArch Studio Collins',
        date: 'Yesterday',
        att: 'Oxford_St_Struct_RevC.pdf',
        read: true,
        type: 'drawings',
        siteId: 'oxford',
      },
    ],
    messages: [
      { id: 'ox-m1', userId: 'james',    text: 'Concrete pour tomorrow 7am. All hands on deck! Make sure pump is positioned by 6:30am. 🏗️', time: '8:45 AM', pinned: true  },
      { id: 'ox-m2', userId: 'marco',    text: 'Formwork is ready, all props checked and tightened. Good to go.',                              time: '9:02 AM', pinned: false },
      { id: 'ox-m3', userId: 'sarah',    text: 'Just got the council compliance email – we need to action the noise management plan today.',    time: '9:18 AM', pinned: false },
      { id: 'ox-m4', userId: 'valentin', text: 'On it – I\'ll update the noise plan and send to council this afternoon.',                       time: '9:25 AM', pinned: false },
      { id: 'ox-m5', userId: 'james',    text: 'Drawings updated. Column C4 moved 300mm east – need structural engineer sign-off before pour!', time: '9:41 AM', pinned: true  },
    ],
    tasks: [
      { id: 'ox-t1', text: 'Update concrete order for 300mm column change',  done: false, priority: 'high', assign: 'james',    due: 'Today'     },
      { id: 'ox-t2', text: 'Action noise compliance plan for council',       done: false, priority: 'high', assign: 'valentin', due: 'Today'     },
      { id: 'ox-t3', text: 'Get structural engineer sign-off on Rev C',      done: false, priority: 'high', assign: 'valentin', due: 'Tomorrow'  },
      { id: 'ox-t4', text: 'Confirm formwork removal schedule',              done: true,  priority: 'med',  assign: 'marco',    due: 'Apr 28'    },
      { id: 'ox-t5', text: 'Safety induction for new labour hire',           done: false, priority: 'low',  assign: 'sarah',    due: 'Apr 30'    },
    ],
    docs: [
      { name: 'DA Consent Certificate',   date: 'Jan 2025' },
      { name: 'Structural Drawings Rev C', date: 'Apr 2025' },
      { name: 'Site Safety Plan',          date: 'Mar 2025' },
      { name: 'Noise Management Checklist', date: 'Apr 2025' },
    ],
  },
  {
    id: 'darling',
    name: 'Darling Harbour Tower',
    shortName: 'Darling Hbr',
    address: '1 Darling Dr, Sydney NSW 2000',
    client: 'Lendlease',
    color: '#4DA6FF',
    status: 'active',
    progress: 68,
    budget: 2400000,
    spent: 1650000,
    phase: 'Structure R+4',
    teamIds: ['valentin', 'james', 'marco', 'luke'],
    emails: [
      {
        id: 'dh-e1',
        fromName: 'BétonPro Supplies',
        from: 'invoices@betonpro.com.au',
        subject: 'Invoice #BP-1139 – Concrete R+4 Darling Harbour',
        body: 'Dear Team,\n\nPlease find below our invoice for concrete supply to Darling Harbour Tower, Level R+4.\n\nPremium concrete 35MPa – 120m³ @ $115/m³: $13,800\nAdditives & fibres: $500\nPump operator (8hrs): $550\n\nTotal: $14,850 (inc. GST)\n\nPayment terms: 30 days EOM.\n\nThank you for your continued business.',
        date: '10:22 AM',
        att: 'Invoice_BP-1139.pdf',
        read: true,
        type: 'invoice',
        siteId: 'darling',
      },
    ],
    messages: [
      { id: 'dh-m1', userId: 'james', text: 'R+4 slab poured and finished. 35 MPa mix confirmed by lab. Looking clean! 💪',  time: '7:55 AM', pinned: true  },
      { id: 'dh-m2', userId: 'marco', text: 'Steel delivery arriving Thursday 8am – need 2 riggers on site.',                  time: '8:30 AM', pinned: false },
      { id: 'dh-m3', userId: 'luke',  text: 'Electrical rough-in on levels 2–3 completed. Ready for inspection.',              time: '9:10 AM', pinned: false },
    ],
    tasks: [
      { id: 'dh-t1', text: 'Organise concrete test cylinder results',    done: false, priority: 'high', assign: 'james',    due: 'Today'    },
      { id: 'dh-t2', text: 'Arrange steel delivery inspection Thursday', done: false, priority: 'high', assign: 'marco',    due: 'Apr 24'   },
      { id: 'dh-t3', text: 'Book electrical inspection for L2–L3',       done: false, priority: 'med',  assign: 'luke',     due: 'Apr 25'   },
      { id: 'dh-t4', text: 'Prepare Lendlease progress report',          done: false, priority: 'med',  assign: 'valentin', due: 'Apr 28'   },
    ],
    docs: [
      { name: 'Lendlease Contract',      date: 'Nov 2024' },
      { name: 'Structural Drawings R+4', date: 'Apr 2025' },
    ],
  },
]

export const INITIAL_NOTIFS: Notification[] = [
  {
    id: 'n1',
    siteId: 'oxford',
    type: 'message',
    text: 'James: Concrete pour 7am tomorrow. All hands on deck!',
    time: '8:45 AM',
    read: false,
  },
  {
    id: 'n2',
    siteId: 'oxford',
    type: 'email',
    text: 'New email routed → Oxford St: Council DA Compliance',
    time: '9:18 AM',
    read: false,
  },
  {
    id: 'n3',
    siteId: 'oxford',
    type: 'urgent',
    text: '⚠️ James flagged URGENT: Update concrete order 300mm',
    time: '9:41 AM',
    read: false,
  },
  {
    id: 'n4',
    siteId: 'darling',
    type: 'message',
    text: 'James: R+4 slab poured. 35 MPa confirmed 💪',
    time: '7:55 AM',
    read: true,
  },
]
